import datetime

x = datetime.datetime.now()
# print(x)
# print(x.year)
# print(x.month)
# print(x.day)
# print(x.time())
# print(x.strftime("%a"))
# print(x.strftime("%A"))
# print(x.strftime("%w"))
# print(x.strftime("%d"))
# print(x.strftime("%b"))
# print(x.strftime("%B"))
# print(x.strftime("%m"))
# print(x.strftime("%y"))
# print(x.strftime("%Y"))

# For Tomorrow:
# x1 = datetime.datetime.now() + datetime.timedelta(days=1)
# print(x1)
# print(x1.year)
# print(x1.month)
# print(x1.day)
# print(x1.time())
# print(x1.strftime("%a"))
# print(x1.strftime("%A"))
# print(x1.strftime("%w"))
# print(x1.strftime("%d"))
# print(x1.strftime("%b"))
# print(x1.strftime("%B"))
# print(x1.strftime("%m"))
# print(x1.strftime("%y"))
# print(x1.strftime("%Y"))

# For Specific Date:
# x2 = datetime.datetime(2021, 3, 18)
# print(x2)
# print(x2.year)
# print(x2.month)
# print(x2.day)
# print(x2.time())
# print(x2.strftime("%a"))
# print(x2.strftime("%A"))
# print(x2.strftime("%w"))
# print(x2.strftime("%d"))
# print(x2.strftime("%b"))
# print(x2.strftime("%B"))
# print(x2.strftime("%m"))
# print(x2.strftime("%y"))
# print(x2.strftime("%Y"))
